---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
#          - centos8
          - debian10
#          - ubuntu2404
#          - ubuntu2204
#          - centos9
#          - geerlingguy/docker-centos8-ansible:latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        # run: pip3 install ansible molecule molecule-docker docker yamllint ansible-lint
        #run: pip3 install ansible molecule molecule-plugins[docker] docker yamllint ansible-lint
        run: pip3 install ansible molecule molecule-docker docker yamllint ansible-lint


      - name: Install test list dependencies.
        run: pip3 list

      - name: Run Molecule tests.
        run: molecule --debug test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
